name: Run Tests On Example App

on:
  workflow_dispatch:

jobs:
  Test_Header_Component:
    uses: ./assignments/week-4/redux-example/.github/workflows/test.yaml
    with:
      working-directory: ./assignments/week-4/redux-example

